"""Training input/output column definitions from the engine spec (§4.4, §7, §11)."""
from __future__ import annotations
from typing import FrozenSet, List

CONSTANT_COLS_TO_DROP: List[str] = [
    "VolAllPExViaBil",
    "VolAgriImViaBil",
    "VolAgriExViaBil",
    "VolCatImViaBil",
    "CusIntTimeExGB-E",
]

TRAINING_COLUMN_ORDER: List[str] = [
    "VolAllPImGB",
    "VolAllPExGB",
    "VolAgriImGB",
    "VolAgriExGB",
    "VolCatImGB",
    "VolCatExGB",
    "VolAllPImEULB",
    "VolAllPExEULB",
    "VolAgriImEULB",
    "VolAgriExEULB",
    "VolCatImEULB",
    "VolCatExEULB",
    "VolAllPImViaChe",
    "VolAllPExViaChe",
    "VolAgriImViaChe",
    "VolAgriExViaChe",
    "VolCatImViaChe",
    "VolCatExViaChe",
    "VolAllPImViaRott",
    "VolAllPExViaRott",
    "VolAgriImViaRott",
    "VolAgriExViaRott",
    "VolCatImViaRott",
    "VolCatExViaRott",
    "VolAllPImViaZee",
    "VolAllPExViaZee",
    "VolAgriImViaZee",
    "VolAgriExViaZee",
    "VolCatImViaZee",
    "VolCatExViaZee",
    "VolAllPImViaBil",
    "VolCatExViaBil",
    "VolAllPImGBEU",
    "VolAllPExGBEU",
    "PerCusIntTrucksAPExIR",
    "CusIntTimeAPExIR",
    "PerCusIntTrucksAgriExIR",
    "CusIntTimeAgriExIR",
    "PerCusIntTrucksCatExIR",
    "CusIntTimeCatExIR",
    "PerGreenTrucksAPImIR",
    "DocChkTimeAPImIR",
    "PerPhyChkAPImIR",
    "PhyChkTimeAPImIR",
    "PerSecurityChkAPIR",
    "SecChkTimeAPImIR",
    "DocChkTimeAgriImIR",
    "PerPhyChkAgriImIR",
    "PhyChkTimeAgriImIR",
    "PerSecurityChkAgriIR",
    "SecChkTimeAgriImIR",
    "DocChkTimeCatImIR",
    "PerPhyChkCatImIR",
    "PhyChkTimeCatImIR",
    "PerSecurityChkCatIR",
    "SecChkTimeCatImIR",
    "PerCusIntTrucksAPExGB-W",
    "CusIntTimeAPExGB-W",
    "PerCusIntTrucksAgriExGB-W",
    "CusIntTimeAgriExGB-W",
    "PerCusIntTrucksCatExGB-W",
    "CusIntTimeCatExGB-W",
    "PerGreenTrucksAPImGB-W",
    "DocChkTimeAPImGB-W",
    "PerPhyChkAPImGB-W",
    "PhyChkTimeAPImGB-W",
    "PerSecChkAPImGB-W",
    "SecChkTimeAPImGB-W",
    "DocChkTimeAgriImGB-W",
    "PerPhyChkAgriImGB-W",
    "PhyChkTimeAgriImGB-W",
    "PerSecChkAgriImGB-W",
    "SecChkTimeAgriImGB-W",
    "DocChkTimeCatImGB-W",
    "PerPhyChkCatImGB-W",
    "PhyChkTimeCatImGB-W",
    "PerSecChkCatImGB-W",
    "SecChkTimeCatImGB-W",
    "PerCusIntTrucksExGB-E",
    "PerGreenTrucksImGB-E",
    "DocChkTimeImGB-E",
    "PerPhyChkImGB-E",
    "PhyChkTimeImGB-E",
    "PerSecChkImGB-E",
    "SecChkTimeImGB-E",
    "PerCusIntTrucksExEU",
    "CusIntTimeExEU",
    "PerGreenTrucksImEU",
    "DocCheckTimeImEU",
    "PerPhyChkImEU",
    "PhyCheckTimeImEU",
    "PerSecurityChkEU",
    "SecCheckTimeEU",
    "TransitCheckTimeLB",
    "PerPhyChkLB",
    "PhyCheckTimeLB",
    "PerSecurityChkLB",
    "SecCheckTimeLB",
    "NumCustomShedD",
    "NumDAFMInspBayD",
    "NumSecurityPostD",
    "NumTractorD",
    "NumCustomShedR",
    "NumDAFMInspBayR",
    "NumSecurityPostR",
    "NumTractorR",
    "NumCustomShedGB-W",
    "NumDAFMInspBayGB-W",
    "NumSecurityPostGB-W",
    "NumTractorGB-W",
    "NumCustomShedHoly",
    "NumDAFMInspBayHoly",
    "NumSecurityPostHoly",
    "NumTractorHoly",
    "NumCustomShedLiv",
    "NumDAFMInspBayLiv",
    "NumSecurityPostLiv",
    "NumTractorLiv",
    "NumCustomShedDov",
    "NumDAFMInspBayDov",
    "NumSecurityPostDov",
    "NumTractorDov",
    "NumCustomShedEU",
    "NumDAFMInspBayEU",
    "NumSecurityPostEU",
    "NumTractorEU",
    "PerUKTrucksMoveD",
    "PerLBTrucksMoveD",
    "DToHeyVesselCap",
    "DToLivVesselCap",
    "DToHolyVesselCap",
    "RToFishVesselCap",
    "RToPemVesselCap",
    "PerProductMoveHey",
    "PerProductMoveLiv",
    "PerProductMoveHoly",
    "PerProductMoveFish",
    "PerProductMovePem",
    "PerLBTrucksMoveToHey",
    "PerLBTrucksMoveToLiv",
    "PerLBTrucksMoveToHoly",
    "PerLBTrucksMoveToFish",
    "PerLBTrucksMoveToPem",
    "DToCheVesselCap",
    "DToRottVesselCap",
    "DToZeeVesselCap",
    "RToCheVesselCap",
    "RToBilVesselCap",
    "AvgShelflife(ProdCat)",
    "UnAccTrucks(%)",
    "DocCheckCost",
    "PhyCheckCost",
    "SecurityCheckCost",
]

OUTPUT_COLUMN_ORDER: List[str] = [
    "Transportation time all P exportto GB",
    "Transportation time all P import from GB",
    "Transportation time agri exportto GB",
    "Transportation time agri import from GB",
    "Transportation time cat exportto GB",
    "Transportation time cat import from GB",
    "Remaining shelflife cat exportto GB",
    "Remaining shelflife cat import from GB",
    "AP cus int WT on ex at D",
    "AP avg WT on im at D",
    "AP doc chk WT on im at D",
    "AP phy chk WT on im at D",
    "AP sec chk WT on im at D",
    "Agri cus int WT on ex at D",
    "Agri avg WT on im at D",
    "Agri doc chk WT on im at D",
    "Agri phy chk WT on im at D",
    "Agri sec chk WT on im at D",
    "Cat cus int WT on ex at D",
    "Cat avg WT on im at D",
    "Cat doc chk WT on im at D",
    "Cat phy chk WT on im at D",
    "Cat sec chk WT on im at D",
    "AP avg WT on ex at R",
    "AP avg WT on im at R",
    "AP doc chk WT on im at R",
    "AP phy chk WT on im at R",
    "AP sec chk WT on im at R",
    "Agri avg WT on ex at R",
    "Agri avg WT on im at R",
    "Agri doc chk WT on im at R",
    "Agri phy chk WT on im at R",
    "Agri sec chk WT on im at R",
    "Cat avg WT on ex at R",
    "Cat avg WT on im at R",
    "Cat doc chk WT on im at R",
    "Cat phy chk WT on im at R",
    "Cat sec chk WT on im at R",
    "AP avg waiting time on ex at fish",
    "AP avg waiting time on im at fish",
    "Agri avg waiting time on ex at fish",
    "Agri avg waiting time on im at fish",
    "Cat avg waiting time on ex at fish",
    "Cat avg waiting time on im at fish",
    "AP avg waiting time on ex at hey",
    "AP avg waiting time on im at hey",
    "Agri avg waiting time on ex at hey",
    "Agri avg waiting time on im at hey",
    "Cat avg waiting time on ex at hey",
    "Cat avg waiting time on im at hey",
    "AP avg waiting time on ex at holy",
    "AP avg waiting time on im at holy",
    "Agri avg waiting time on ex at holy",
    "Agri avg waiting time on im at holy",
    "Cat avg waiting time on ex at holy",
    "Cat avg waiting time on im at holy",
    "AP avg waiting time on ex at liv",
    "AP avg waiting time on im at liv",
    "Agri avg waiting time on ex at liv",
    "Agri avg waiting time on im at liv",
    "Cat avg waiting time on ex at liv",
    "Cat avg waiting time on im at liv",
    "AP avg waiting time on ex at pem",
    "AP avg waiting time on im at pem",
    "Agri avg waiting time on ex at pem",
    "Agri avg waiting time on im at pem",
    "Cat avg waiting time on ex at pem",
    "Cat avg waiting time on im at pem",
    "D custom shed utilisation",
    "DDAFM insp bay utilisation",
    "D security post utilisation",
    "D tractor utilisation",
    "R custom shed utilisation",
    "RDAFM insp bay utilisation",
    "R security post utilisation",
    "R tractor utilisation",
    "Fish custom shed utilisation",
    "Fish DAFM insp bay utilisation",
    "Fish security post utilisation",
    "Hey custom shed utilisation",
    "Hey DAFM insp bay utilisation",
    "Hey security post utilisation",
    "Holy custom shed utilisation",
    "Holy DAFM insp bay utilisation",
    "Holy security post utilisation",
    "Liv custom shed utilisation",
    "Liv DAFM insp bay utilisation",
    "Liv security post utilisation",
    "Pem custom shed utilisation",
    "Pem DAFM insp bay utilisation",
    "Pem security post utilisation",
    "Trucks vessel queue length D to UK",
    "Trucks vessel queue length R to UK",
    "Trucks vessel queue length hey to D",
    "Trucks vessel queue length liv to D",
    "Trucks vessel queue length holy to D",
    "Trucks vessel queue length fish to R",
    "Trucks vessel queue length pem to R",
    "Total doc check cost ex trucks from IR to GBW",
    "Total phy check cost ex trucks from IR to GBW",
    "Total sec check cost ex trucks from IR to GBW",
    "Transportation time exportto EULB",
    "Transportation time import from EULB",
    "Remaining shelflife cat exportto EULB",
    "Remaining shelflife cat import from EULB",
    "Transportation time exportto EU che",
    "Transportation time import from EU che",
    "Remaining shelflife cat exportto EU che",
    "Remaining shelflife cat import from EU che",
    "Transportation time exportto EU ro ze",
    "Transportation time import from EU ro ze",
    "Remaining shelflife cat exportto EU ro ze",
    "Remaining shelflife cat import from EU ro ze",
    "Transportation time exportto EU bil",
    "Transportation time import from EU bil",
    "Remaining shelflife cat exportto EU bil",
    "Remaining shelflife cat import from EU bil",
    "Avg waiting time on ex at dov",
    "Avg waiting time on im at dov",
    "Avg waiting time on ex at cal",
    "Avg waiting time on im at cal",
    "Trucks vessel queue length D to che",
    "Trucks vessel queue length D to rott",
    "Trucks vessel queue length D to zee",
    "Trucks vessel queue length R to che",
    "Trucks vessel queue length R to bil",
    "Trucks vessel queue length che to IR",
    "Trucks vessel queue length rott to D",
    "Trucks vessel queue length zee to D",
    "Trucks vessel queue length bil to R",
    "Total doc check cost im trucks to D",
    "Total phy check cost im trucks to D",
    "Total sec check cost im trucks to D",
    "Total doc check cost im trucks to R",
    "Total phy check cost im trucks to R",
    "Total sec check cost im trucks to R",
]

_INPUT_SET: FrozenSet[str] = frozenset(TRAINING_COLUMN_ORDER)
_OUTPUT_SET: FrozenSet[str] = frozenset(OUTPUT_COLUMN_ORDER)

# Spec §4.1 — Phase 1 = first 101 targets; remaining 35 are Phase 2 (EU / placeholder).
PHASE_1_OUTPUT_COUNT: int = 101
PHASE_2_OUTPUT_COUNT: int = 35


def output_phase_index(idx: int) -> int:
    """1-based output index position ``idx`` (0..135) → phase 1 or 2."""
    return 1 if idx < PHASE_1_OUTPUT_COUNT else 2


def validate_column_lists() -> None:
    """Assert invariants; call at import in tests or data_loader."""
    assert len(TRAINING_COLUMN_ORDER) == 153
    assert len(OUTPUT_COLUMN_ORDER) == 136
    assert PHASE_1_OUTPUT_COUNT + PHASE_2_OUTPUT_COUNT == len(OUTPUT_COLUMN_ORDER)
    assert len(_INPUT_SET) == 153
    assert len(_OUTPUT_SET) == 136
    assert not (_INPUT_SET & _OUTPUT_SET)
    for c in CONSTANT_COLS_TO_DROP:
        assert c not in _INPUT_SET

